server:
  port: 9000

spring:
  application:
    name: auth-server

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth-server:
  issuer: ${AUTH_SERVER_ISSUER:http://localhost:9000}
