server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: bff

spring:
  application:
    name: bff-web

legacy:
  api:
    url: http://localhost:8090   # mismo legacy-api en HTTP

management:
  endpoints:
    web:
      exposure:
        include: health,info
