server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: bff

spring:
  application:
    name: bff-mobile

legacy:
  api:
    url: http://localhost:8090   # legacy en HTTP por ahora

management:
  endpoints:
    web:
      exposure:
        include: health,info
