server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: bff
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain,text/xml,text/html
    min-response-size: 1024

spring:
  application:
    name: bff-mobile

legacy:
  api:
    url: http://localhost:8090   # legacy en HTTP por ahora

management:
  endpoints:
    web:
      exposure:
        include: health,info
