server:
  port: 8444
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: bff
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/plain,text/xml,text/html
    min-response-size: 1024

spring:
  application:
    name: bff-mobile
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER:http://localhost:9000}
          jwk-set-uri: ${AUTH_SERVER_JWKS_URI:${AUTH_SERVER_ISSUER:http://localhost:9000}/oauth2/jwks}

legacy:
  api:
    url: ${LEGACY_API_URL:http://localhost:8090}   # legacy en HTTP por ahora

management:
  endpoints:
    web:
      exposure:
        include: health,info
