spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER_ISSUER:http://localhost:9000}
          jwk-set-uri: ${AUTH_SERVER_JWKS_URI:${AUTH_SERVER_ISSUER:http://localhost:9000}/oauth2/jwks}
legacy:
  api:
    url: ${LEGACY_API_URL:http://localhost:8090}
